ALTER TABLE bookmarks ADD COLUMN image_zoom REAL NOT NULL DEFAULT 1;
ALTER TABLE folders ADD COLUMN image_zoom REAL NOT NULL DEFAULT 1;
ALTER TABLE games ADD COLUMN image_zoom REAL NOT NULL DEFAULT 1;
